
-- ============================================================
--  Government Scheme Eligibility Checker — Database
-- ============================================================

CREATE TABLE IF NOT EXISTS schemes (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT    NOT NULL,
    category        TEXT    NOT NULL,
    sub_category    TEXT,
    ministry        TEXT,
    scheme_type     TEXT    DEFAULT 'Central',
    target_group    TEXT    NOT NULL,
    eligibility     TEXT    NOT NULL,
    description     TEXT,
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eligibility_rules (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    scheme_id       INTEGER NOT NULL REFERENCES schemes(id) ON DELETE CASCADE,
    field           TEXT    NOT NULL,
    operator        TEXT    NOT NULL,
    value           TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS applicants (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT    NOT NULL,
    age             INTEGER NOT NULL CHECK (age > 0 AND age < 130),
    gender          TEXT    NOT NULL CHECK (gender IN ('Male','Female','Other')),
    occupation      TEXT    NOT NULL,
    yearly_income   REAL    NOT NULL CHECK (yearly_income >= 0),
    submitted_at    DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS check_results (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    applicant_id    INTEGER NOT NULL REFERENCES applicants(id) ON DELETE CASCADE,
    scheme_id       INTEGER NOT NULL REFERENCES schemes(id)    ON DELETE CASCADE,
    is_eligible     INTEGER NOT NULL DEFAULT 0,
    checked_at      DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rules_scheme   ON eligibility_rules(scheme_id);
CREATE INDEX IF NOT EXISTS idx_results_app    ON check_results(applicant_id);
CREATE INDEX IF NOT EXISTS idx_results_scheme ON check_results(scheme_id);

INSERT INTO schemes (name, category, sub_category, ministry, scheme_type, target_group, eligibility, description) VALUES
('PM Kisan Samman Nidhi Variant 152', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('PM Kisan Samman Nidhi Variant 95', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('PM Kisan Samman Nidhi Variant 14', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('PM Fasal Bima Yojana Variant 192', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Ayushman Bharat Variant 27', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('PM Fasal Bima Yojana Variant 143', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Kisan Samman Nidhi Variant 176', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('MGNREGA Variant 142', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Atal Pension Yojana Variant 17', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Mid-Day Meal Scheme Variant 74', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Ayushman Bharat Variant 186', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('PM Fasal Bima Yojana Variant 170', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Kisan Samman Nidhi Variant 102', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Atal Pension Yojana Variant 56', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Ayushman Bharat Variant 56', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Mid-Day Meal Scheme Variant 184', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('MGNREGA Variant 28', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('PM Fasal Bima Yojana Variant 182', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Kisan Samman Nidhi Variant 148', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('MGNREGA Variant 145', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('PM Kisan Samman Nidhi Variant 197', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Atal Pension Yojana Variant 71', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('PM Fasal Bima Yojana Variant 72', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Atal Pension Yojana Variant 53', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Ayushman Bharat Variant 174', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 3', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 147', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('PM Kisan Samman Nidhi Variant 22', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Ayushman Bharat Variant 191', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('MGNREGA Variant 197', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Mid-Day Meal Scheme Variant 154', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Ayushman Bharat Variant 52', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 91', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Atal Pension Yojana Variant 178', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Ayushman Bharat Variant 140', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('MGNREGA Variant 5', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Atal Pension Yojana Variant 24', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Ayushman Bharat Variant 187', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Atal Pension Yojana Variant 176', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Mid-Day Meal Scheme Variant 8', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Ayushman Bharat Variant 45', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('PM Kisan Samman Nidhi Variant 56', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Atal Pension Yojana Variant 184', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Ayushman Bharat Variant 200', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('MGNREGA Variant 36', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Mid-Day Meal Scheme Variant 180', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Ayushman Bharat Variant 32', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Atal Pension Yojana Variant 63', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Mid-Day Meal Scheme Variant 55', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Ayushman Bharat Variant 88', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 197', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Mid-Day Meal Scheme Variant 80', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('PM Fasal Bima Yojana Variant 191', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Fasal Bima Yojana Variant 149', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Mid-Day Meal Scheme Variant 66', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Ayushman Bharat Variant 188', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Atal Pension Yojana Variant 114', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Atal Pension Yojana Variant 44', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Ayushman Bharat Variant 148', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('PM Fasal Bima Yojana Variant 156', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Kisan Samman Nidhi Variant 143', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Atal Pension Yojana Variant 145', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Ayushman Bharat Variant 180', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('PM Kisan Samman Nidhi Variant 109', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Mid-Day Meal Scheme Variant 136', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('MGNREGA Variant 63', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Ayushman Bharat Variant 76', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('MGNREGA Variant 23', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('PM Fasal Bima Yojana Variant 61', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('MGNREGA Variant 14', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Ayushman Bharat Variant 114', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 4', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 5', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Mid-Day Meal Scheme Variant 5', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('PM Fasal Bima Yojana Variant 13', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Atal Pension Yojana Variant 41', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('PM Kisan Samman Nidhi Variant 116', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Mid-Day Meal Scheme Variant 25', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('PM Fasal Bima Yojana Variant 101', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Kisan Samman Nidhi Variant 122', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('PM Fasal Bima Yojana Variant 200', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Mid-Day Meal Scheme Variant 92', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('PM Fasal Bima Yojana Variant 176', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Atal Pension Yojana Variant 66', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Mid-Day Meal Scheme Variant 116', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Mid-Day Meal Scheme Variant 9', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('PM Fasal Bima Yojana Variant 72', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Fasal Bima Yojana Variant 155', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Fasal Bima Yojana Variant 160', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Ayushman Bharat Variant 38', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('PM Fasal Bima Yojana Variant 4', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Kisan Samman Nidhi Variant 188', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Ayushman Bharat Variant 94', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('MGNREGA Variant 148', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('PM Kisan Samman Nidhi Variant 35', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('MGNREGA Variant 171', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('MGNREGA Variant 72', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('MGNREGA Variant 118', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('PM Kisan Samman Nidhi Variant 139', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('PM Fasal Bima Yojana Variant 148', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Mid-Day Meal Scheme Variant 167', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('PM Kisan Samman Nidhi Variant 72', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Atal Pension Yojana Variant 180', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('MGNREGA Variant 90', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Atal Pension Yojana Variant 52', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('Atal Pension Yojana Variant 66', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('PM Kisan Samman Nidhi Variant 119', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('MGNREGA Variant 136', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Mid-Day Meal Scheme Variant 46', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Ayushman Bharat Variant 33', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('PM Kisan Samman Nidhi Variant 68', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('MGNREGA Variant 194', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Ayushman Bharat Variant 141', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 114', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Mid-Day Meal Scheme Variant 106', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Atal Pension Yojana Variant 18', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('PM Fasal Bima Yojana Variant 196', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Ayushman Bharat Variant 71', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 32', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Ayushman Bharat Variant 163', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Mid-Day Meal Scheme Variant 153', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('Mid-Day Meal Scheme Variant 68', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('PM Fasal Bima Yojana Variant 103', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Fasal Bima Yojana Variant 176', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('PM Kisan Samman Nidhi Variant 60', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('PM Fasal Bima Yojana Variant 34', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('MGNREGA Variant 76', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment'),
('Ayushman Bharat Variant 7', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('Mid-Day Meal Scheme Variant 6', 'Education', 'Food', 'Ministry of Education', 'Central', 'Students', 'Must be enrolled in a recognized institution', 'Free meals'),
('PM Fasal Bima Yojana Variant 161', 'Agriculture', 'Insurance', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Crop insurance'),
('Atal Pension Yojana Variant 102', 'Pension', 'Retirement', 'Ministry of Finance', 'Central', 'Unorganized Workers', 'Must be working in unorganized sector', 'Pension after retirement'),
('PM Kisan Samman Nidhi Variant 190', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('PM Kisan Samman Nidhi Variant 62', 'Agriculture', 'Income Support', 'Ministry of Agriculture', 'Central', 'Farmers', 'Must be a registered farmer with cultivable land', 'Provides ₹6000 per year'),
('Ayushman Bharat Variant 147', 'Health', 'Insurance', 'Ministry of Health', 'Central', 'Poor', 'Belong to BPL category', 'Health insurance'),
('MGNREGA Variant 194', 'Employment', 'Jobs', 'Ministry of Rural Development', 'Central', 'Rural Population', 'Resident of rural area', '100 days employment');

INSERT INTO eligibility_rules (scheme_id, field, operator, value) VALUES
(1, 'occupation', 'eq', 'Farmer'),
(1, 'yearly_income', 'lte', '200000'),
(2, 'occupation', 'eq', 'Farmer'),
(2, 'yearly_income', 'lte', '200000'),
(3, 'occupation', 'eq', 'Farmer'),
(3, 'yearly_income', 'lte', '200000'),
(4, 'occupation', 'eq', 'Farmer'),
(5, 'yearly_income', 'lte', '100000'),
(6, 'occupation', 'eq', 'Farmer'),
(7, 'occupation', 'eq', 'Farmer'),
(7, 'yearly_income', 'lte', '200000'),
(8, 'yearly_income', 'lte', '150000'),
(8, 'age', 'gte', '18'),
(9, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(9, 'age', 'gte', '18'),
(9, 'age', 'lte', '40'),
(10, 'occupation', 'eq', 'Student'),
(11, 'yearly_income', 'lte', '100000'),
(12, 'occupation', 'eq', 'Farmer'),
(13, 'occupation', 'eq', 'Farmer'),
(13, 'yearly_income', 'lte', '200000'),
(14, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(14, 'age', 'gte', '18'),
(14, 'age', 'lte', '40'),
(15, 'yearly_income', 'lte', '100000'),
(16, 'occupation', 'eq', 'Student'),
(17, 'yearly_income', 'lte', '150000'),
(17, 'age', 'gte', '18'),
(18, 'occupation', 'eq', 'Farmer'),
(19, 'occupation', 'eq', 'Farmer'),
(19, 'yearly_income', 'lte', '200000'),
(20, 'yearly_income', 'lte', '150000'),
(20, 'age', 'gte', '18'),
(21, 'occupation', 'eq', 'Farmer'),
(21, 'yearly_income', 'lte', '200000'),
(22, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(22, 'age', 'gte', '18'),
(22, 'age', 'lte', '40'),
(23, 'occupation', 'eq', 'Farmer'),
(24, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(24, 'age', 'gte', '18'),
(24, 'age', 'lte', '40'),
(25, 'yearly_income', 'lte', '100000'),
(26, 'yearly_income', 'lte', '100000'),
(27, 'yearly_income', 'lte', '100000'),
(28, 'occupation', 'eq', 'Farmer'),
(28, 'yearly_income', 'lte', '200000'),
(29, 'yearly_income', 'lte', '100000'),
(30, 'yearly_income', 'lte', '150000'),
(30, 'age', 'gte', '18'),
(31, 'occupation', 'eq', 'Student'),
(32, 'yearly_income', 'lte', '100000'),
(33, 'yearly_income', 'lte', '100000'),
(34, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(34, 'age', 'gte', '18'),
(34, 'age', 'lte', '40'),
(35, 'yearly_income', 'lte', '100000'),
(36, 'yearly_income', 'lte', '150000'),
(36, 'age', 'gte', '18'),
(37, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(37, 'age', 'gte', '18'),
(37, 'age', 'lte', '40'),
(38, 'yearly_income', 'lte', '100000'),
(39, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(39, 'age', 'gte', '18'),
(39, 'age', 'lte', '40'),
(40, 'occupation', 'eq', 'Student'),
(41, 'yearly_income', 'lte', '100000'),
(42, 'occupation', 'eq', 'Farmer'),
(42, 'yearly_income', 'lte', '200000'),
(43, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(43, 'age', 'gte', '18'),
(43, 'age', 'lte', '40'),
(44, 'yearly_income', 'lte', '100000'),
(45, 'yearly_income', 'lte', '150000'),
(45, 'age', 'gte', '18'),
(46, 'occupation', 'eq', 'Student'),
(47, 'yearly_income', 'lte', '100000'),
(48, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(48, 'age', 'gte', '18'),
(48, 'age', 'lte', '40'),
(49, 'occupation', 'eq', 'Student'),
(50, 'yearly_income', 'lte', '100000'),
(51, 'yearly_income', 'lte', '100000'),
(52, 'occupation', 'eq', 'Student'),
(53, 'occupation', 'eq', 'Farmer'),
(54, 'occupation', 'eq', 'Farmer'),
(55, 'occupation', 'eq', 'Student'),
(56, 'yearly_income', 'lte', '100000'),
(57, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(57, 'age', 'gte', '18'),
(57, 'age', 'lte', '40'),
(58, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(58, 'age', 'gte', '18'),
(58, 'age', 'lte', '40'),
(59, 'yearly_income', 'lte', '100000'),
(60, 'occupation', 'eq', 'Farmer'),
(61, 'occupation', 'eq', 'Farmer'),
(61, 'yearly_income', 'lte', '200000'),
(62, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(62, 'age', 'gte', '18'),
(62, 'age', 'lte', '40'),
(63, 'yearly_income', 'lte', '100000'),
(64, 'occupation', 'eq', 'Farmer'),
(64, 'yearly_income', 'lte', '200000'),
(65, 'occupation', 'eq', 'Student'),
(66, 'yearly_income', 'lte', '150000'),
(66, 'age', 'gte', '18'),
(67, 'yearly_income', 'lte', '100000'),
(68, 'yearly_income', 'lte', '150000'),
(68, 'age', 'gte', '18'),
(69, 'occupation', 'eq', 'Farmer'),
(70, 'yearly_income', 'lte', '150000'),
(70, 'age', 'gte', '18'),
(71, 'yearly_income', 'lte', '100000'),
(72, 'yearly_income', 'lte', '100000'),
(73, 'yearly_income', 'lte', '100000'),
(74, 'occupation', 'eq', 'Student'),
(75, 'occupation', 'eq', 'Farmer'),
(76, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(76, 'age', 'gte', '18'),
(76, 'age', 'lte', '40'),
(77, 'occupation', 'eq', 'Farmer'),
(77, 'yearly_income', 'lte', '200000'),
(78, 'occupation', 'eq', 'Student'),
(79, 'occupation', 'eq', 'Farmer'),
(80, 'occupation', 'eq', 'Farmer'),
(80, 'yearly_income', 'lte', '200000'),
(81, 'occupation', 'eq', 'Farmer'),
(82, 'occupation', 'eq', 'Student'),
(83, 'occupation', 'eq', 'Farmer'),
(84, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(84, 'age', 'gte', '18'),
(84, 'age', 'lte', '40'),
(85, 'occupation', 'eq', 'Student'),
(86, 'occupation', 'eq', 'Student'),
(87, 'occupation', 'eq', 'Farmer'),
(88, 'occupation', 'eq', 'Farmer'),
(89, 'occupation', 'eq', 'Farmer'),
(90, 'yearly_income', 'lte', '100000'),
(91, 'occupation', 'eq', 'Farmer'),
(92, 'occupation', 'eq', 'Farmer'),
(92, 'yearly_income', 'lte', '200000'),
(93, 'yearly_income', 'lte', '100000'),
(94, 'yearly_income', 'lte', '150000'),
(94, 'age', 'gte', '18'),
(95, 'occupation', 'eq', 'Farmer'),
(95, 'yearly_income', 'lte', '200000'),
(96, 'yearly_income', 'lte', '150000'),
(96, 'age', 'gte', '18'),
(97, 'yearly_income', 'lte', '150000'),
(97, 'age', 'gte', '18'),
(98, 'yearly_income', 'lte', '150000'),
(98, 'age', 'gte', '18'),
(99, 'occupation', 'eq', 'Farmer'),
(99, 'yearly_income', 'lte', '200000'),
(100, 'occupation', 'eq', 'Farmer'),
(101, 'occupation', 'eq', 'Student'),
(102, 'occupation', 'eq', 'Farmer'),
(102, 'yearly_income', 'lte', '200000'),
(103, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(103, 'age', 'gte', '18'),
(103, 'age', 'lte', '40'),
(104, 'yearly_income', 'lte', '150000'),
(104, 'age', 'gte', '18'),
(105, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(105, 'age', 'gte', '18'),
(105, 'age', 'lte', '40'),
(106, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(106, 'age', 'gte', '18'),
(106, 'age', 'lte', '40'),
(107, 'occupation', 'eq', 'Farmer'),
(107, 'yearly_income', 'lte', '200000'),
(108, 'yearly_income', 'lte', '150000'),
(108, 'age', 'gte', '18'),
(109, 'occupation', 'eq', 'Student'),
(110, 'yearly_income', 'lte', '100000'),
(111, 'occupation', 'eq', 'Farmer'),
(111, 'yearly_income', 'lte', '200000'),
(112, 'yearly_income', 'lte', '150000'),
(112, 'age', 'gte', '18'),
(113, 'yearly_income', 'lte', '100000'),
(114, 'yearly_income', 'lte', '100000'),
(115, 'occupation', 'eq', 'Student'),
(116, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(116, 'age', 'gte', '18'),
(116, 'age', 'lte', '40'),
(117, 'occupation', 'eq', 'Farmer'),
(118, 'yearly_income', 'lte', '100000'),
(119, 'yearly_income', 'lte', '100000'),
(120, 'yearly_income', 'lte', '100000'),
(121, 'occupation', 'eq', 'Student'),
(122, 'occupation', 'eq', 'Student'),
(123, 'occupation', 'eq', 'Farmer'),
(124, 'occupation', 'eq', 'Farmer'),
(125, 'occupation', 'eq', 'Farmer'),
(125, 'yearly_income', 'lte', '200000'),
(126, 'occupation', 'eq', 'Farmer'),
(127, 'yearly_income', 'lte', '150000'),
(127, 'age', 'gte', '18'),
(128, 'yearly_income', 'lte', '100000'),
(129, 'occupation', 'eq', 'Student'),
(130, 'occupation', 'eq', 'Farmer'),
(131, 'occupation', 'in', 'Daily Wage Worker,Self-employed,Unemployed'),
(131, 'age', 'gte', '18'),
(131, 'age', 'lte', '40'),
(132, 'occupation', 'eq', 'Farmer'),
(132, 'yearly_income', 'lte', '200000'),
(133, 'occupation', 'eq', 'Farmer'),
(133, 'yearly_income', 'lte', '200000'),
(134, 'yearly_income', 'lte', '100000'),
(135, 'yearly_income', 'lte', '150000'),
(135, 'age', 'gte', '18');
